version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure
  
  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './vol/wordpress'
      #home/ecolin/data
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './vol/mariadb'
      #home/ecolin/data

networks:
  inception:
    driver: bridge